# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AOCashBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AOCashBox


  target 'AOCashBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AOCashBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
